title: ''
subtitle: ''
description: Detailed description goes here
recon_title: Software Composition Analysis Report
recon_subtitle: Project Title
recon_description: Detailed description goes here
estimation_title: ''
estimation_subtitle: ''
estimation_description: Detailed description goes here
